### PR TITLE
Fix for printing contents of Input

### LINKED ISSUE #52: Input values are not getting printed.
**Form controls values are not getting displayed in print screen**
For example, if I have an element like below.
`              <input name="shipTo" #shipTo="ngModel" [(ngModel)]="invoiceService.formDate.shipTo" type="text" class="form-control" placeholder="Ship To" [disabled]="invoiceService.formDate.paymentStatus=='Paid'">`

It is not getting displayed. 

Can anyone look into this and let me know as soon as possible.
Web page as shown in the screen shot.
image

Print Screen as shown below.
image

### LINKED ISSUE #68: Ngx Print not working with input values - ngModel Values
I have a html form and many input values which are using ngModel for to and fro communication. But when im using ngx-print in this form, all the input values are getting empty and showing a preview to download as pdf. Also tried the same in stackblitz. Please check the image
issue

### PR DESCRIPTION
**Pull request by broem**
Resolves #68, resolves #52

### CODE REVIEW

**Comment by broem** [comment]
@selemxmn are you alive?

**Comment by selemxmn** [comment]
@broem Merged & released, do you mind please if I would add you as a maintainer on the npm repository ? I'm not available here for most of the time for some reasons.. Thanks

**Comment by broem** [comment]
@selemxmn that would be fine with me.

**Comment by selemxmn** [comment]
@broem Thank you very much indeed ! However, I could not find your username under NPM?

**Comment by broem** [comment]
sorry about that, try now

**Comment by selemxmn** [comment]
@broem done ! Thank you again !

**Pull request merged**
