### PR TITLE
Update ngx-print.directive.ts

### PR DESCRIPTION
**Pull request by MiroKov**
update printDirective to work on IE11.

### CODE REVIEW

**Comment by MiroKov** [comment]
@selemxmn Could you please merge this? We need this to run on IE.

**Comment by MiroKov** [comment]
@broem Hi Ben, could you please merge this? We need this in production. Thanks in advance.

**Comment by MiroKov** [comment]
@broem Thanks Ben,
when can we expect a new release?

**Comment by selemxmn** [comment]
@MiroKov Released (1.2.0-beta.4)
Sorry, there are always strings attached by my side, thus I'm not a 100% available.. should comeback soon to clean it up.
Thanks for using `ngx-print`.

**Pull request merged**
